---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/alexvasquez.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_alexvasquez/
      - /bin/rsync -av ./ $DEPLOYPATH