---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/alexvasquez.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_alexvasquez/
      - /bin/rsync -av ./ $DEPLOYPATH